# frozen_string_literal: true

require "has_state_machine/deprecation"
require "has_state_machine/machine"
require "has_state_machine/state"
require "has_state_machine/state_helpers"

module HasStateMachine
  module Definition
    extend ActiveSupport::Concern

    OPTION_KEYS = %i[state_attribute attribute workflow_namespace state_validations_on_object prefix scopes].freeze

    class_methods do
      # Declares one machine per state attribute. The first machine is primary
      # for the class and instance readers. Unknown options warn and are ignored.
      #
      # @param states [Array<String, Symbol>] allowed states; the first is the default
      # @param options [Hash]
      # @option options [String, Symbol] :state_attribute (:status) state column
      # @option options [String, Symbol] :attribute alias for :state_attribute
      # @option options [String] :workflow_namespace ("Workflow::<Model>") state-class namespace; unique per model
      # @option options [Boolean] :state_validations_on_object (true) run state validations on the model
      # @option options [Boolean, String, Symbol] :prefix scope/predicate prefix; true uses the state attribute
      # @option options [Boolean] :scopes (true) generate scopes
      #
      # @example
      #   class Post < ApplicationRecord
      #     has_state_machine states: %i(draft published archived)
      #     has_state_machine states: %i(available removing),
      #       state_attribute: :deletion_state,
      #       workflow_namespace: "Workflow::PostDeletion",
      #       prefix: :deletion
      #   end
      def has_state_machine(states: [], **options)
        raise ArgumentError, "Please define at least one state to use has_state_machine." if states.empty?

        machine = build_machine(states, options)
        redeclared = register_machine(machine)

        include HasStateMachine::StateHelpers

        # A redeclaration only swaps the configuration, as in 1.x; the methods
        # and validations generated by the first declaration stay in place.
        define_state_machine_methods(machine) unless redeclared
      end

      private

      def build_machine(states, options)
        options = normalize_options(options)

        HasStateMachine::Machine.new(
          states: states,
          state_attribute: options[:state_attribute],
          workflow_namespace: options[:workflow_namespace],
          state_validations_on_object: options.fetch(:state_validations_on_object, true),
          prefix: options[:prefix],
          scopes: options.fetch(:scopes, true)
        )
      end

      # Assign a new registry so subclass declarations cannot mutate the parent's.
      # @return [Boolean] whether an existing definition was replaced
      def register_machine(machine)
        unless respond_to?(:state_machine_definitions)
          class_attribute :state_machine_definitions, instance_accessor: false, instance_predicate: false,
            default: {}.freeze
        end

        existing = state_machine_definitions
        replaced = existing.key?(machine.state_attribute)
        others = existing.except(machine.state_attribute)

        ensure_unique_namespace!(machine, others)
        detect_conflicts!(machine) if !replaced && others.any?

        self.state_machine_definitions = existing.merge(machine.state_attribute => machine).freeze
        replaced
      end

      def normalize_options(options)
        options = options.symbolize_keys
        warn_about_unknown_options(options)

        if options[:state_attribute] && options[:attribute] &&
            options[:state_attribute].to_sym != options[:attribute].to_sym
          HasStateMachine::Deprecation.warn(
            "has_state_machine on #{self} received both state_attribute: #{options[:state_attribute].inspect} " \
            "and attribute: #{options[:attribute].inspect}; attribute: is ignored."
          )
        end

        options.merge(state_attribute: (options[:state_attribute] || options[:attribute])&.to_sym || :status)
      end

      def warn_about_unknown_options(options)
        unknown = options.keys - OPTION_KEYS
        return if unknown.empty?

        HasStateMachine::Deprecation.warn(
          "has_state_machine on #{self} received unknown option(s) #{unknown.map(&:inspect).join(", ")}, " \
          "which are ignored. Known options: #{OPTION_KEYS.map(&:inspect).join(", ")}."
        )
      end

      def ensure_unique_namespace!(machine, existing)
        namespace = machine.workflow_namespace_for(self).to_s
        clash = existing.each_value.find { |other| other.workflow_namespace_for(self).to_s == namespace }
        return unless clash

        raise ArgumentError,
          "The state machines on #{clash.state_attribute.inspect} and #{machine.state_attribute.inspect} " \
          "of #{self} would both use the workflow namespace #{namespace.inspect}. " \
          "Pass a distinct workflow_namespace: to has_state_machine."
      end

      # The first machine may override existing methods for 1.x compatibility;
      # additional machines must not overwrite scopes or predicates.
      def detect_conflicts!(machine)
        active_record = defined?(ActiveRecord::Base) && self < ActiveRecord::Base

        machine.states.each do |state|
          predicate = machine.predicate_name(state)
          if method_defined?(predicate) || private_method_defined?(predicate)
            raise_conflict(machine, "an instance", predicate)
          end

          next unless active_record && machine.scopes?

          scope_name = machine.scope_name(state)
          raise_conflict(machine, "a class", scope_name) if respond_to?(scope_name, true)
        end
      end

      def raise_conflict(machine, type, method_name)
        raise ArgumentError,
          "You tried to define a state machine on #{machine.state_attribute.inspect} on the model #{self}, " \
          "but this will generate #{type} method #{method_name.to_s.inspect}, which is already defined by " \
          "another state machine or method. Pass prefix: (or scopes: false) to has_state_machine."
      end
    end
  end
end
