name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0']
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Lint
        run: bundle exec rake lint

      - name: Test against rails main
        run: |
          bundle exec appraisal rails-main bundle install
          bundle exec appraisal rails-main rake test

      - name: Test against rails 7.0
        run: |
          bundle exec appraisal rails-7-0 bundle install
          bundle exec appraisal rails-7-0 rake test

      - name: Test against rails 6.1
        run: |
          bundle exec appraisal rails-6-1 bundle install
          bundle exec appraisal rails-6-1 rake test
